#!/bin/bash
python /Users/anbr3575/LRTAnalysis/pando/pipelinepando.py /Users/anbr3575/LRTAnalysis/degreesequences/Freshwater_stream_webs_Coweeta17_Biological_Food_web_n3.gml_directedindistribution.txt /Users/anbr3575/LRTAnalysis/output/Freshwater_stream_webs_Coweeta17_Biological_Food_web_n3.gml_directedindistribution.txtorder4.csv
