#!/bin/bash
python /Users/anbr3575/LRTAnalysis/pando/pipelinepando.py /Users/anbr3575/LRTAnalysis/degreesequences/Freshwater_stream_webs_Blackrock_Biological_Food_web_n3.gml_directedtotaldistribution.txt /Users/anbr3575/LRTAnalysis/output/Freshwater_stream_webs_Blackrock_Biological_Food_web_n3.gml_directedtotaldistribution.txtorder4.csv
