#!/bin/bash
python /Users/anbr3575/LRTAnalysis/pando/pipelinepando.py /Users/anbr3575/LRTAnalysis/degreesequences/US_Congress_roll-call_votes_1789-2009_Rollcall_US_Senate_35_Social_Political_n2.gml_weighted3distribution.txt /Users/anbr3575/LRTAnalysis/output/US_Congress_roll-call_votes_1789-2009_Rollcall_US_Senate_35_Social_Political_n2.gml_weighted3distribution.txtorder4.csv
