#!/bin/bash
python /Users/anbr3575/LRTAnalysis/pando/pipelinepando.py /Users/anbr3575/LRTAnalysis/degreesequences/Metabolic_networks_from_KEGG_2006_mge_Biological_Metabolic_n3.gml_multigraphsimplified_largestcompdistribution.txt /Users/anbr3575/LRTAnalysis/output/Metabolic_networks_from_KEGG_2006_mge_Biological_Metabolic_n3.gml_multigraphsimplified_largestcompdistribution.txtorder4.csv
